spring.application.name=musicplay

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/musicdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1080}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

musicplay.upload-dir=${MUSICPLAY_UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:25MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:40MB}

jwt.secret=${JWT_SECRET:musicplay-secret-key-2026-very-strong-and-long}
jwt.expiration=${JWT_EXPIRATION:3600000}
