-- MusicPlay - script completo para PostgreSQL
-- Ejecutar desde psql conectado a una base administrativa, por ejemplo:
-- psql -U postgres -f sql/musicplay_postgresql_completo.sql

DROP DATABASE IF EXISTS musicdb;
CREATE DATABASE musicdb;

\connect musicdb

DROP TABLE IF EXISTS usuario_oauth CASCADE;
DROP TABLE IF EXISTS historial_reproduccion CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS usuario_artista_preferido CASCADE;
DROP TABLE IF EXISTS usuario_genero_preferido CASCADE;
DROP TABLE IF EXISTS usuario_album CASCADE;
DROP TABLE IF EXISTS usuario_playlist CASCADE;
DROP TABLE IF EXISTS canciones_album CASCADE;
DROP TABLE IF EXISTS canciones_playlist CASCADE;
DROP TABLE IF EXISTS playlist CASCADE;
DROP TABLE IF EXISTS song CASCADE;
DROP TABLE IF EXISTS album CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS genero CASCADE;
DROP TABLE IF EXISTS artista CASCADE;
DROP TABLE IF EXISTS rol CASCADE;

CREATE TABLE rol (
    rol_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_nombre VARCHAR(255)
);

CREATE TABLE artista (
    artista_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artista_nombre VARCHAR(255),
    artista_foto_ruta VARCHAR(255)
);

CREATE TABLE genero (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_genero VARCHAR(255)
);

CREATE TABLE usuario (
    usuario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_nombre VARCHAR(255),
    rol_id INTEGER,
    "usuario_contraseña" VARCHAR(255),
    usuario_correo VARCHAR(255),
    usuario_inicios_sesion INTEGER NOT NULL DEFAULT 0,
    usuario_preferencias_configuradas BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (rol_id)
        REFERENCES rol (rol_id)
);

CREATE TABLE album (
    album_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_nombre VARCHAR(255),
    artista_album BIGINT,
    album_portada_ruta VARCHAR(255),
    CONSTRAINT fk_album_artista
        FOREIGN KEY (artista_album)
        REFERENCES artista (artista_id)
);

CREATE TABLE song (
    song_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    song_nombre VARCHAR(255),
    song_artista BIGINT,
    song_compositor VARCHAR(255),
    song_genero BIGINT,
    song_archivo_ruta VARCHAR(255),
    song_portada_ruta VARCHAR(255),
    CONSTRAINT fk_song_artista
        FOREIGN KEY (song_artista)
        REFERENCES artista (artista_id),
    CONSTRAINT fk_song_genero
        FOREIGN KEY (song_genero)
        REFERENCES genero (id)
);

CREATE TABLE playlist (
    playlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_nombre VARCHAR(255),
    playlist_portada_ruta VARCHAR(255),
    usuario_id BIGINT,
    CONSTRAINT fk_playlist_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE CASCADE
);

CREATE TABLE canciones_album (
    cancion_id BIGINT NOT NULL,
    album_id BIGINT NOT NULL,
    PRIMARY KEY (cancion_id, album_id),
    CONSTRAINT fk_canciones_album_cancion
        FOREIGN KEY (cancion_id)
        REFERENCES song (song_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_canciones_album_album
        FOREIGN KEY (album_id)
        REFERENCES album (album_id)
        ON DELETE CASCADE
);

CREATE TABLE canciones_playlist (
    cancion_id BIGINT NOT NULL,
    playlist_id BIGINT NOT NULL,
    PRIMARY KEY (cancion_id, playlist_id),
    CONSTRAINT fk_canciones_playlist_cancion
        FOREIGN KEY (cancion_id)
        REFERENCES song (song_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_canciones_playlist_playlist
        FOREIGN KEY (playlist_id)
        REFERENCES playlist (playlist_id)
        ON DELETE CASCADE
);

CREATE TABLE usuario_playlist (
    usuario_id BIGINT NOT NULL,
    playlist_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, playlist_id),
    CONSTRAINT fk_usuario_playlist_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_usuario_playlist_playlist
        FOREIGN KEY (playlist_id)
        REFERENCES playlist (playlist_id)
        ON DELETE CASCADE
);

CREATE TABLE usuario_album (
    usuario_id BIGINT NOT NULL,
    album_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, album_id),
    CONSTRAINT fk_usuario_album_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_usuario_album_album
        FOREIGN KEY (album_id)
        REFERENCES album (album_id)
        ON DELETE CASCADE
);

CREATE TABLE usuario_genero_preferido (
    usuario_id BIGINT NOT NULL,
    genero_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, genero_id),
    CONSTRAINT fk_usuario_genero_preferido_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_usuario_genero_preferido_genero
        FOREIGN KEY (genero_id)
        REFERENCES genero (id)
        ON DELETE CASCADE
);

CREATE TABLE usuario_artista_preferido (
    usuario_id BIGINT NOT NULL,
    artista_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, artista_id),
    CONSTRAINT fk_usuario_artista_preferido_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_usuario_artista_preferido_artista
        FOREIGN KEY (artista_id)
        REFERENCES artista (artista_id)
        ON DELETE CASCADE
);

CREATE TABLE likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    cancion_id BIGINT,
    CONSTRAINT fk_likes_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_likes_cancion
        FOREIGN KEY (cancion_id)
        REFERENCES song (song_id)
        ON DELETE CASCADE,
    CONSTRAINT uk_likes_usuario_cancion
        UNIQUE (usuario_id, cancion_id)
);

CREATE TABLE historial_reproduccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    cancion_id BIGINT,
    fecha_reproduccion TIMESTAMP,
    duracion_reproduccion INTEGER,
    CONSTRAINT fk_historial_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_historial_cancion
        FOREIGN KEY (cancion_id)
        REFERENCES song (song_id)
        ON DELETE CASCADE
);

CREATE TABLE usuario_oauth (
    oauth_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oauth_proveedor VARCHAR(255) NOT NULL,
    oauth_proveedor_id VARCHAR(255) NOT NULL,
    oauth_correo VARCHAR(255),
    usuario_id BIGINT NOT NULL,
    CONSTRAINT uk_usuario_oauth_provider
        UNIQUE (oauth_proveedor, oauth_proveedor_id),
    CONSTRAINT fk_usuario_oauth_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_usuario_correo
    ON usuario (usuario_correo)
    WHERE usuario_correo IS NOT NULL;

CREATE UNIQUE INDEX uk_usuario_nombre
    ON usuario (usuario_nombre)
    WHERE usuario_nombre IS NOT NULL;

CREATE INDEX idx_album_artista
    ON album (artista_album);

CREATE INDEX idx_song_artista
    ON song (song_artista);

CREATE INDEX idx_song_genero
    ON song (song_genero);

CREATE INDEX idx_playlist_usuario
    ON playlist (usuario_id);

CREATE INDEX idx_historial_fecha
    ON historial_reproduccion (fecha_reproduccion DESC);

CREATE INDEX idx_usuario_genero_preferido_genero
    ON usuario_genero_preferido (genero_id);

CREATE INDEX idx_usuario_artista_preferido_artista
    ON usuario_artista_preferido (artista_id);

INSERT INTO rol (rol_id, rol_nombre)
VALUES
    (1, 'ROLE_ADMIN'),
    (2, 'ROLE_USER')
ON CONFLICT (rol_id) DO UPDATE
SET rol_nombre = EXCLUDED.rol_nombre;

SELECT setval(pg_get_serial_sequence('rol', 'rol_id'), COALESCE((SELECT MAX(rol_id) FROM rol), 1), true);
